server:
  port: 8765
  ssl:
    key-store: ssl/docker/server.p12
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: docker

spring:
  application:
    name: gateway
    
info:
  component: Zuul Server

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

eureka:  
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
    healthcheck:
      enabled: true      
  instance:
    hostname: docker
    non-secure-port-enabled: false
    secure-port-enabled: true
    secure-port: ${server.port}
    
security:
  basic:
    enabled: true
  user:
    password: none
  oauth2:
    client:
      clientId: userinterface
      clientSecret: userinterface
      accessTokenUri: http://userauthentication:8095/oauth/token
      userAuthorizationUri: http://userauthentication:8095/oauth/authorize
    resource:
      user-info-uri: http://userauthentication:8095/user
    
zuul:
  sensitive-headers: 
  routes:
    discovery:
      url: http://discovery:8761
      

# Aumentando o timeout do gateway
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000
  
  